### PR TITLE
build: update gradle wrapper to 7.6

### PR DESCRIPTION
**Pull request by yeikel**
I generated this pull request using the wrapper itself

` ./gradlew wrapper --gradle-version 7.6`

I also configured the checksum verification as it was missing 

> 
> Here are the highlights of this release:
>  - Added support for Java 19.
>  - Introduced `--rerun` flag for individual task rerun.
>  - Improved dependency block for test suites to be strongly typed.
>  - Added a pluggable system for Java toolchains provisioning.
> 
> For more details see https://docs.gradle.org/7.6/release-notes.html

### CODE REVIEW

**Comment by timtebeek** [comment]
Perhaps we should add the GitHub Action to verify the checksum here before we merge this one; would you agree?

**Comment by timtebeek** [comment]
Added into #75

**Comment by yeikel** [comment]
> Perhaps we should add the GitHub Action to verify the checksum here before we merge this one; would you agree?

According to this comment: 
https://github.com/openrewrite/rewrite/pull/2646#issuecomment-1383013177

It might not be necessary to add it in the first place as it is part of the base CI

**Comment by timtebeek** [comment]
You're right, thanks! Missed that one; I'll remove the files again from the PRs.

**Pull request closed without merging**
